name = "Theseus S 3 . 5"
author = "ExplosiveJoe190"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "988a440b37c230e823766fc999d0f0a5c8e92cc4d5dde33e5ceb9d2185a33c61"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
