name = "Theseus S 3 . 5"
author = "ExplosiveJoe190"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d86c8b99556d674c7d578ccf71e211c34796c4eaeb54c955e8e351e26804e245"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
