name = "Theseus S 3 . 5"
author = "ExplosiveJoe190"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "830e5d0e870c43a45d7b7028cf84a1f75fc019cfb6ec9dc819f8af0183d5af7a"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
